# Generated by Django 5.2 on 2025-05-10 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(default='student', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('syllabus', models.TextField(blank=True)),
                ('meeting_times', models.CharField(blank=True, max_length=100)),
                ('seat_limit', models.PositiveIntegerField(default=0)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='CourseEnrollment.course')),
                ('instructor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='CourseEnrollment.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(default=django.utils.timezone.now)),
                ('final_grade', models.CharField(blank=True, default='n/a', max_length=3, null=True)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='CourseEnrollment.course')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='CourseEnrollment.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseEnrollment.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHourSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to='CourseEnrollment.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='CourseEnrollment.myuser')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseEnrollment.officehourslot')),
            ],
        ),
        migrations.CreateModel(
            name='OverrideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='override_requests', to='CourseEnrollment.course')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='override_requests', to='CourseEnrollment.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='CourseEnrollment.course')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='CourseEnrollment.myuser')),
            ],
        ),
    ]
