# Generated by Django 5.2 on 2025-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseEnrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fullName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
