# Generated by Django 5.2 on 2025-05-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseEnrollment', '0003_alter_myuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='waitlist_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
