# Generated by Django 5.2 on 2025-05-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseEnrollment', '0005_alter_enrollment_course_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='CourseEnrollment.course'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='CourseEnrollment.myuser'),
        ),
    ]
